### ISSUE TITLE
reservations page : service types

### ISSUE THREAD

**Issue by Leslie303** [IST303S19/ProjectTeam2#6]
Hello, 
In the existing reservations section of the Reservations page, I expect to see a column for each type of service MiYE offers. 
However, right now it only shows "massage."

We'll need to get this corrected...

**Comment by nosivads** [comment]
Currently the list is of current reservations; does not include all services if there are no reservations. If we change this behavior then we need to include both current reservations and current offerings (because list can include offerings that have been delected).

**Comment by nosivads** [comment]
Done.

**Comment by Leslie303** [comment]
kewl
________________________________
