### ISSUE TITLE
Canceled appointments

### ISSUE THREAD

**Issue by nosivads** [IST303S19/ProjectTeam2#7]
Needs some testing. Canceled appointments are currently not charged for (if within policy) but continue to appear. Should guests be able to book at that time if canceled? If so, need to update the reservation validation piece.

**Comment by Leslie303** [comment]
yes. new people can book over canceled reservations. i thought i got that working before. i'll take a look.
________________________________

**Comment by nosivads** [comment]
Problem not replicated. May have been a database update issue. Closing issue.

**Comment by nosivads** [comment]
Sometimes cancelled appointments can't be replaced. Reopening issue.

**Comment by nosivads** [comment]
Problem only occurred when a new reservation was made for the same customer at the same time as a previously cancelled reservation. Very specific! Fixed. Closing.
