### ISSUE TITLE
List of available times for services

### ISSUE THREAD

**Issue by nosivads** [IST303S19/ProjectTeam2#9]
For each category the last time available listed is 7:45pm.
Should be:
7:45 for 15 mins
7:30 for 30 mins
7:15 for 45 mins
etc.

**Comment by Leslie303** [comment]
good catch
________________________________

**Comment by nosivads** [comment]
Partially fixed. List is now correct for "today" but not for subsequent days of the week.

**Comment by nosivads** [comment]
Fixed
